included:
  - App
  - Tests

excluded:
  - .git
  - DerivedData

opt_in_rules:
  - empty_count
  - sorted_imports

disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 700
  error: 900

type_body_length:
  warning: 350
  error: 500

function_body_length:
  warning: 80
  error: 120

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
