schemaVersion: 1
sessionDefaultsProfiles:
  macos:
    projectPath: /Users/dlq/Developer/Parliaments/Parliaments.xcodeproj
    scheme: Parliaments
    configuration: Release
    arch: arm64
    suppressWarnings: false
    preferXcodebuild: true
    platform: macOS
  ios:
    projectPath: /Users/dlq/Developer/Parliaments/Parliaments.xcodeproj
    scheme: Parliaments
    configuration: Debug
    simulatorName: iPhone 17
    simulatorPlatform: iOS Simulator
    useLatestOS: true
    suppressWarnings: false
    preferXcodebuild: true
    platform: iOS Simulator
  tvos:
    projectPath: /Users/dlq/Developer/Parliaments/Parliaments.xcodeproj
    scheme: Parliaments
    configuration: Debug
    simulatorName: Apple TV
    simulatorPlatform: tvOS Simulator
    useLatestOS: true
    suppressWarnings: false
    preferXcodebuild: true
    platform: tvOS Simulator
activeSessionDefaultsProfile: macos
